source ~/dotfiles/bash/.bashprompt
alias vim='nvim'
alias ..='cd ..'
alias gcl='git clone'
alias gst='git status'
alias ga='git add'
alias gcm='git commit'
alias gps='git push'
alias gbr='git branch'
alias gco='git checkout'
alias gpl='git pull'
alias gft='git fetch'
